const LBoardUtilities = [
  {
    efficiency: '100',
    goalsBalance: '6',
    goalsFavor: '9',
    goalsOwn: '3',
    name: 'Santos',
    totalDraws: '0',
    totalGames: '3',
    totalLosses: '0',
    totalPoints: '9',
    totalVictories: '3',
  },
  {
    efficiency: '100',
    goalsBalance: '6',
    goalsFavor: '8',
    goalsOwn: '2',
    name: 'Corinthians',
    totalDraws: '0',
    totalGames: '3',
    totalLosses: '0',
    totalPoints: '9',
    totalVictories: '3',
  },
  {
    efficiency: '77.78',
    goalsBalance: '5',
    goalsFavor: '10',
    goalsOwn: '5',
    name: 'Palmeiras',
    totalDraws: '1',
    totalGames: '3',
    totalLosses: '0',
    totalPoints: '7',
    totalVictories: '2',
  },
  {
    efficiency: '100',
    goalsBalance: '3',
    goalsFavor: '4',
    goalsOwn: '1',
    name: 'Grêmio',
    totalDraws: '0',
    totalGames: '2',
    totalLosses: '0',
    totalPoints: '6',
    totalVictories: '2',
  },
  {
    efficiency: '100',
    goalsBalance: '2',
    goalsFavor: '2',
    goalsOwn: '0',
    name: 'Real Brasília',
    totalDraws: '0',
    totalGames: '2',
    totalLosses: '0',
    totalPoints: '6',
    totalVictories: '2',
  },
  {
    efficiency: '66.67',
    goalsBalance: '3',
    goalsFavor: '4',
    goalsOwn: '1',
    name: 'São Paulo',
    totalDraws: '1',
    totalGames: '2',
    totalLosses: '0',
    totalPoints: '4',
    totalVictories: '1',
  },
  {
    efficiency: '44.44',
    goalsBalance: '-2',
    goalsFavor: '4',
    goalsOwn: '6',
    name: 'Internacional',
    totalDraws: '1',
    totalGames: '3',
    totalLosses: '1',
    totalPoints: '4',
    totalVictories: '1',
  },
  {
    efficiency: '44.44',
    goalsBalance: '-2',
    goalsFavor: '2',
    goalsOwn: '4',
    name: 'Botafogo',
    totalDraws: '1',
    totalGames: '3',
    totalLosses: '1',
    totalPoints: '4',
    totalVictories: '1',
  },
  {
    efficiency: '50',
    goalsBalance: '1',
    goalsFavor: '3',
    goalsOwn: '2',
    name: 'Ferroviária',
    totalDraws: '0',
    totalGames: '2',
    totalLosses: '1',
    totalPoints: '3',
    totalVictories: '1',
  },
  {
    efficiency: '33.33',
    goalsBalance: '0',
    goalsFavor: '2',
    goalsOwn: '2',
    name: 'Napoli-SC',
    totalDraws: '2',
    totalGames: '2',
    totalLosses: '0',
    totalPoints: '2',
    totalVictories: '0',
  },
  {
    efficiency: '16.67',
    goalsBalance: '-1',
    goalsFavor: '2',
    goalsOwn: '3',
    name: 'Cruzeiro',
    totalDraws: '1',
    totalGames: '2',
    totalLosses: '1',
    totalPoints: '1',
    totalVictories: '0',
  },
  {
    efficiency: '16.67',
    goalsBalance: '-1',
    goalsFavor: '1',
    goalsOwn: '2',
    name: 'Flamengo',
    totalDraws: '1',
    totalGames: '2',
    totalLosses: '1',
    totalPoints: '1',
    totalVictories: '0',
  },
  {
    efficiency: '11.11',
    goalsBalance: '-3',
    goalsFavor: '3',
    goalsOwn: '6',
    name: 'Minas Brasília',
    totalDraws: '1',
    totalGames: '3',
    totalLosses: '2',
    totalPoints: '1',
    totalVictories: '0',
  },
  {
    efficiency: '11.11',
    goalsBalance: '-4',
    goalsFavor: '3',
    goalsOwn: '7',
    name: 'Avaí/Kindermann',
    totalDraws: '1',
    totalGames: '3',
    totalLosses: '2',
    totalPoints: '1',
    totalVictories: '0',
  },
  {
    efficiency: '0',
    goalsBalance: '-3',
    goalsFavor: '2',
    goalsOwn: '5',
    name: 'São José-SP',
    totalDraws: '0',
    totalGames: '3',
    totalLosses: '3',
    totalPoints: '0',
    totalVictories: '0',
  },
  {
    efficiency: '0',
    goalsBalance: '-4',
    goalsFavor: '0',
    goalsOwn: '4',
    name: 'Bahia',
    totalDraws: '0',
    totalGames: '3',
    totalLosses: '3',
    totalPoints: '0',
    totalVictories: '0',
  },
];

export default LBoardUtilities;
